#!/usr/bin/env bash

set -euo pipefail

curl -sSL https://get.haskellstack.org/ | sh
stack setup --resolver lts-11.4
git clone https://github.com/darklang/elm-format
cd elm-format && git checkout elm-escape && stack install -j 4

