#!/usr/bin/env bash

set -euo pipefail

~/.local/bin/elm-format --json --elm-version 0.18 --stdin < $1 \
  | ../src/philip2.exe > out 2> stderr \
  && esy ocamlformat --inplace out

code=$?
cat out
cat stderr >&2
if [ code = 0 ]; then
  rm out
  rm stderr
fi

exit $code
